### ISSUE TITLE
Provide Backround Image for Hero Sections

### ISSUE THREAD

**Issue by bryantjderosier** [bryantjderosier/marx-llc#7]
- provide a new background image for hero section if we do not want to use the free stock image that is in the markup.

**Comment by davidlezette** [comment]
![marx-background-medium-size-black-and-white](https://user-images.githubusercontent.com/8398275/52755975-d9c6db00-2fcd-11e9-90a8-1d2cd5aa1f19.jpg)

![marx-background-medium-size-black-and-white-w-white-opaque-cover](https://user-images.githubusercontent.com/8398275/52755960-cae02880-2fcd-11e9-81c5-f05b94c763a3.jpg)

Let's go with this image for the main header background. I'm not sure if the opaque white part of the image shown in your example is done using CSS or not, so I provided two images: one that should have a white opaque filter applied 60% transparency should work, or the other which shouldn't require any CSS styling.  
I may decide to use a different image after I see how it looks on the development server. 

Cheers,
